description: 'Default Deployment plan

  '
environments:
- path: overcloud-resource-registry-puppet.yaml
- path: environments/network-isolation.yaml
- path: ispras-extra/environments/extra/advanced.yaml
- path: ispras-extra/environments/extra/net-custom.yaml
- path: ispras-extra/environments/extra/disable-telemetry.yaml
- path: ispras-extra/environments/extra/fixed-ips.yaml
- path: ispras-extra/environments/extra/containers-prepare-parameter.yaml
- path: ispras-extra/environments/extra/net-config-data-lookup.yaml
- path: ispras-extra/environments/extra/podman.yaml
- path: ispras-extra/environments/extra/os-net-config-mappings.yaml
- path: ispras-extra/environments/extra/ispras-services.yaml
- path: ispras-extra/environments/features/cinder-iscsi-backend.yaml
- path: ispras-extra/environments/features/nonha-arch.yaml
- path: ispras-extra/environments/extra/michman.yaml
name: overcloud
passwords:
  AdminPassword: veryhardpass
  AdminToken: qAw2WJe7nO36oGq9O2QZzCdW8
  AodhPassword: z8drV46WHpjK24FjASndT3qtY
  BarbicanPassword: Qy9vuD8sMEIBASnzBaV6In53N
  BarbicanSimpleCryptoKek: TmNbWn23nWJOxmgW2QmL26OGwrQ2mwDnxCPXlZ0TLoU=
  CeilometerMeteringSecret: jNpcg77letfl8DhXvtwtiHmNQ
  CeilometerPassword: b5mR4JDPN9qkEhFRiQi1CZ4gB
  CephClientKey: AQA4eGJjAAAAABAAZjdG6gF7i7WjU3Oe6nHSaA==
  CephClusterFSID: ebd7fe1f-2e65-41f2-a044-ccd511bbfe60
  CephDashboardAdminPassword: 7qFv22m4pqKyh9S2123hp2Fpd
  CephGrafanaAdminPassword: YUfbmCMIKIUKZD6n5f27NTRTu
  CephManilaClientKey: AQA4eGJjAAAAABAA6rligVMSX9j+TTpANW0DlA==
  CephRgwKey: AQA4eGJjAAAAABAAPEmr3iiPx/rdzP0GWCemXQ==
  CinderPassword: TNvHKsjphEHJu0PO0Oz7FhDKq
  CongressPassword: CkEIzY63CKoUtlNOezw4ouGxF
  DesignatePassword: lin3cGg10PGxvRyBaWry5j8ln
  DesignateRndcKey: yR69Ih/Qw1KbDB0o+ihraGTrtfOfD/eV/9bgjMCpnO4=
  Ec2ApiPassword: 5B2yKKyEBLSBVCyF5Xi6Cl48c
  EtcdInitialClusterToken: XZUT3fNphuKrwl0U0oYCN7uic
  GlancePassword: f7e97wQHLZ9GXfxDTAIOM0u7i
  GnocchiPassword: TQH9zEFg2EqzeK62X5vGevJxS
  HAProxyStatsPassword: 7RmTJSSyodBBBst6HH3bFbpw0
  HeatAuthEncryptionKey: z9IG0TIsZabHRZdXc6lij97YbcXvYWZK
  HeatPassword: R0Dpa6wIXz6BDzMqgXCFoS19Z
  HeatStackDomainAdminPassword: yFG5rYDRkUKS0NMWN8S2nACFM
  HorizonSecret: CuOUOeEmyA
  IronicPassword: 1YNC7px22tkj8Jjc3pYI1YSAI
  KeystoneCredential0: 8CWs5I4AbJykEaE1hTtZ-HyLbVgGKs-6m4_ykeIU_l8=
  KeystoneCredential1: -cHo-Yhw0rCcCoTgz_6hsJkOXWl5K46WB55D5oLptP8=
  KeystoneFernetKey0: XpEpTev-jvrz38ts3gFezAUyzsgyat2oi3ji3sm6tGE=
  KeystoneFernetKey1: HF9Lzd6idec-alnoNkZjCNTeOS2j3j64XLuUiiGEZqw=
  KeystoneFernetKeys: "/etc/keystone/fernet-keys/0:\n  content: 8jo26z5YPu7WBqfewoImdJ5JLZ8NT2ywIh5mSNJe9_8=\n\
    /etc/keystone/fernet-keys/1:\n  content: FmzDfohGa912nqBDcT4hx86C2G0juMcaSV-QkNQ_RD4="
  LibvirtTLSPassword: 7i6fLAViyplkvszbnAwrGNwp2
  ManilaPassword: uYPHY0h1rBecYhUj0u3wareio
  MigrationSshKey: "private_key: '-----BEGIN RSA PRIVATE KEY-----\n\n  MIIEowIBAAKCAQEA1BSzOeps5mUxydbRTia6M3qbLhxpCAf+y7p2gsVx53Kqa/gU\n\
    \n  RhyE/zeqOxpZZ6b+wWYNP/B1LWNsgSYFKlOvxaeyTT1py3au350bE/VnT590hjit\n\n  q86d2GwHHY9dVT7F9vWHvdJb7FOMrLnl8LNG6XgIG54a6PdfGMSY/OHJhh6yjUT9\n\
    \n  Y0LFKY1iMZxBXlX2fKDjtzDOQ0rTD92mlybxVDMP0o6JfQEDuEP6Jbr4Lbz/hikJ\n\n  3rnQdaqufkyKUiFciVOFervbwU+/BrpHtQWJUL5bur43tXq0ygrVX9urq/f1iTAz\n\
    \n  tH02hXH3QlY1RltLLFNbm3NOy5pbaqo6nhLOKwIDAQABAoIBAFH2bg3D+7JPCZ7n\n\n  1pxNe0jJ6Y84i57++AnkVkjT5eF8/0Aa8Droar331WJiHItijrJPrm83jxGrixOe\n\
    \n  jgB9t0C8Prx7L5fillL1dLGR9gtfpLj6zqPHhllN5rIV5gw75mY7HerOkZgT8hoO\n\n  /j64Cn/QU9HYmK3QbIA1+qpA2JFsN4+oVGDLZmbTzcc7x78PhBzVIKUw2WarA1G+\n\
    \n  JHU+FvNWCgbWRqiNpCN0MNG7m/ulZDH9Xj5Q5+nAHlMttT36QHaadfw9zsClHpXe\n\n  4vw+Z+lq1nlKcRSltY4ES+KuPDtQ/L4Ut7NXDFprmE5588Hd+5FoGFqZA8u/JXCR\n\
    \n  aDlyWoECgYEA7jB2xaExCPy5wXgfDfTe+XeLUpfAGqcVMUzceA7RkQK0+D8rUQ+e\n\n  ZONX7OEV6xyKE9Mg5rB6RQQZawYeQ9vgKp26phsYQi6b8DbV0m7VoTMi9tkfCgKV\n\
    \n  BklK903C/Vf5+Bd4sEEueTX988E/Cpmcymx9Avpvma7CLCb9jp6aPRUCgYEA4/B0\n\n  lckv51TUY86T2givEpC3Jh9s1aghzSKQuZN3YCRnUQRs8uZ4ACzQCAiFigCHLXGu\n\
    \n  iwwiX1k6gD4AlejBnXRM5kJ9zvSqHM+YMwTWwghk5WfWtGtZXmory5B1Md7GRwkS\n\n  BGuOyHQ+nn2ChmlKQOB3pHKWZvRimnyHthOULj8CgYEAl/zu3R8FZiG1+oFG96Xo\n\
    \n  XjFtAq/4kklJmaLdD/MMwMaEaeANKPWZcfEr2uiqDtOwPAQ9+1ZjPwTln0hRKaX1\n\n  PdxWDMY/TYPmV3r2KAg3Y1x5FCDp0H5jT5aXMoU5RmXMCQYZKgb9u7S7Lr6CFqZ8\n\
    \n  ySI/BxZ8/gjouDnNFCOach0CgYBpt9Ca2CD7rgCD+f/hFD3+4lfPuquDvONQfUOa\n\n  jqbDVJ8GmILfdb0ad65Uy38ELpKDpUJLA2m9x2i2qgsjfDywhoxUD2rCXf+4NSBm\n\
    \n  KUxh2frR24NdUpy0iZGebHWul6BmufI9UpV6q0+Puq6bIKJrzLAw+WSAg8Bn3nIj\n\n  JJmJiQKBgDWA9Op+v8OsXNeVEKAvo5oU3aitQ1QigjK39XlLDiu2NjDuTN75pYgu\n\
    \n  TVZyOfyXhmKs9xlMo9DvEEIAGm9IDWP2/PpkvjUHKRpPmvygO6dAGUv0Ng11ADKQ\n\n  L+6OPqGfcvgB9l6f80qFHTun9nFitksCNny1Cgld7mY1sbjM4WJN\n\
    \n  -----END RSA PRIVATE KEY-----\n\n  '\npublic_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDUFLM56mzmZTHJ1tFOJrozepsuHGkIB/7LunaCxXHncqpr+BRGHIT/N6o7Gllnpv7BZg0/8HUtY2yBJgUqU6/Fp7JNPWnLdq7fnRsT9WdPn3SGOK2rzp3YbAcdj11VPsX29Ye90lvsU4ysueXws0bpeAgbnhro918YxJj84cmGHrKNRP1jQsUpjWIxnEFeVfZ8oOO3MM5DStMP3aaXJvFUMw/Sjol9AQO4Q/oluvgtvP+GKQneudB1qq5+TIpSIVyJU4V6u9vBT78Guke1BYlQvlu6vje1erTKCtVf26ur9/WJMDO0fTaFcfdCVjVGW0ssU1ubc07LmltqqjqeEs4r\n\
    \  Generated by TripleO\n"
  MistralPassword: gjS0EEo9vNON0aPf8HffvzMsC
  MysqlClustercheckPassword: o9VMBGWuVsx3G9blotzoGlOxj
  MysqlRootPassword: LT7tUy9dzQ
  NeutronMetadataProxySharedSecret: WkD0T1BR1CQFpFLvzPYJsEBEb
  NeutronPassword: rQB5UgvtzHXSfEVVbykreJhnw
  NotifyPassword: ignKL4dpBlA3Vpx9Mrpp6K2bK
  NovaPassword: on0bXyvKgJAMSZHEDjChDEETn
  NovajoinPassword: Jtx6hPQSyJA7AKrK6QQk780cW
  OctaviaCaKeyPassphrase: tdcTD9SKx5hlaO00uYDecxstR
  OctaviaHeartbeatKey: WlAAnAfqN22aA7Q9YcSLnvsCx
  OctaviaPassword: PnVcTNbOMNTVii3uwWWyBKt7A
  OctaviaServerCertsKeyPassphrase: 1hIOShsFtxkn15if4nTKflHWE205dNfC
  PacemakerRemoteAuthkey: pP6SHB5xYuLLKRKkOIVhnMeLgBSirPtCsxpK1XkSTLANtYhQjb0PaUy9tKF9dQ0UcfKRnkJt7HKOwDmzCwUdLS8PILGuEZX9BKYoSN9cuXkNNdP4zpOMGv24rnTSAJjo9ORoaGyef8X5ZAeJk1kKCfkZyhNlyD2dbZOJW515dbApg1WJW8nUD4rM85fNu2ndn24EJWClVmarbSKzbmjixCQ666DaqnvGYYpvrHIafO3nfs5FctX5B5ZQkqkSwEIdQD8ZjDOz8wNkLXE8dq8Euh422voULiA2hP1E9CvCPF0vH2mNgjZFIdjkGWfJGjPNuxMi8mgmweEY9HuOkyX992fIVgSPXJLcfznnmHFfnTFSB3fpq7gg5rMadIaFkGCpDfGESO38mr2yQeo5b6bG3Rae6l6x5VPmmGWeauXEiKhWTtV8wXI2fBSgObYGWIkYu2w13b4giXr9s3t6nLnRzJAVUkb6aIc9cWfn0RSXqgoRYXlZTJDBpMSnauL0XdInI1Z6Ww57FoT0eG52ecN2gwtpRLcBIXJigsxPIUT2FdPFiHeSUNNlfiIrjSHT4NIyuw5x6sDw4VLjOsfyfCmoNO8GbouGGuIY5NduoZwMDcmZ6SchWSNBvoQzGdazEBuFs3ZDsU1oHibV0C6PpYQPOwOG07QEpkam7hnkaJDQR8t6Lros33t9G7t1pXkwwtFJXEbjl36C7UJtquQbrEwYJKtR0bKHYtsU8VJl59QrSN30bBOfAfrqLHKpaydHYdzFFxa6mhxlgv8HMV7R5PlQvoknxq1dJPXZV3yPLa67x4mE26M2SNHYQQDYktjbMeqjQWkYOeyV3jchB1XD048AeszueKw9Qre5BH4GjP14nmymjB5SC6JiBwkUcEtrpu0U8KSWLamKnqr1yb8L4KzQG28LPXNrnjGwHY5oxyeOBXNlSC3daW6W794PigRRVSOGscTzcNG3Q6zdbJIfBoJpMky2th9rqtSnbs2WTgSnYgaYV396Cnify7FIQyldaUkGFTT3iT2Yol9yfmcilzwcPJF8YsrT5vSz3I3Ixb3Fttsbg6nW1Z7S5fTz6gkHTN34bpwcdXHAHMIBzFgEXbqn9YKYpByBEKlGQ5cctZx27U3MaoJDdAoPWwbsFx39sKqIUGRaFDZllJYxgH2YsvJ1j6JlYJirSy7rejs6h7YkxRsXal7icMdAp25QaA1Hr2bY4V1ehmYyqEfiZdOoxeaqk57LVjzFbRFl5Aad9nL0hwlI4xW0KmliPuoqEUy7Uh0UNbjVTdSIO8STg3nPGEv32G4PFr54SsFSiwuDNtJKoBpLPfI7E1Ifn5HeLO7hO2jy50vzK3CVefzBujmuRgIFCKgPsS6KiUaiAv0ZiyyrlyceiYfaazXaTFdHuEj9P6NvpOUZOYT3A8YmFpBA8nm33Rxi7vpz5rqwKUjbuVWXyMqlUvTq22HjKX6CjHJYTR1JpuCsvY6yhzm34tWmGHXeYVSkPuFHURabf7M5z5a3bvSN9ieOi5NGZyL5ae08jCTNiDo93wwiG4EWIFSzfDSGbv4vYZXUmaPr5eTMqh5bUSu4XNlp50a4FyKN7Y2eLpgxLMm5PfG0IvWkU0zwBfSWeBOwpqvCI6xAjYEJ9HfMT55PexhitUs0dadl1HleDNkAWcVEv9dqgpJVMXE9qZfeCoeo2nmYJV8d0CO2I7JK9GLLUTeOlZFq6MvYu25gisnhXSVWYEvT4P2Q2di4GkgNT9i4mUlDk2vCaIt103UmcnFzG7umwrnaDNnwkeyxr0Qs9Bf5G72Y7mcNcQ03ASNqW9KqEmJePaUNgtkcGbZGqd0RCFSmgYS8QtupoaKwveguLhjPjREFUsUtkjb9C7hrLaWahimNW7b7zOsIf1K5zy8qBOoUjoCQXMtL1W7mkZRpU9b0fZjBnCej4QTyRMAJ20mzsNDs3bU569QQdobU0WBmmdlqWqmDTu8Kjd4FdDbAS3Zgjh1f6s7OYTBp9eqjuVrFCf43PwFqXsK9IgubUglJRBsXZMpzfDba0EiLPCw43vEGtUEwgsPUIbaKg9Iaug8h7dqNLlH939sMiHq3FAEpFc857Cqxo4PVD2ZZNqJQpV1W0WJzC1a0SXEIgzeMNdmtn6k6nR2iWy3H62m3SA8qlXWRTPJIc2heAVXyWJcki12SwGeJaEK9g5DzlqvziaVM1ZeXd5zpwRTMwayRZdNuNhtB7vpGx0Rs7hHY8efaiWGGLq2qtk9GAB5KMaarNQMqHqf64l56pOjPP36vocLVxmQqI5uHUqp46Tmfb1rmh3t6HR4SIS5pybtbxt97Df1qhvPTAgRbU0rGZinLXUfdnfg6YgnQ0i6QcCA59lLdwpYbkHHj4kWaNLx72ozN4v9x6pJnuYxmnF6QcbGUxnuJpyQBLMbhVnNHGgmb8nMMxctUT8zM98PGYOjKnBKusT3HN1gfYs0Zcrdrm3Wrx0DSY87nNRJQpZETio9nRYF0Shgnh5irkWJlO86t5l02VcaurMNcgKYprz0oBuuGwHCVGH48YA5MpLavMdDtgvnRLPnMmiY7BQ1PqTn4WU2Uqw740D9DjJPXj94s7iCVl4VuhjNLkETUNsLVrH7huDBLbbSm5kBZn0DZMD32E6HcBT1paXy00zqqdcer4yG9djm946Zc10RDYBPLWu0QP1nDlsJEsyQ2k6MB9n37sb7kLXg0VH51yBtxyykeKcqdBaKxpRwFpsWQITL88Ts84zmmILLtbMFPKKvHwklfn2u0IT7IGWdblm7Gv59yYGSzHZND8T9koc3YV0Gg2VYhZE2VdMpaac8Fh9lczeP3bq56vGqJ4rKWikCfgp3jhDUS4P52hJAUxFX21TUYjT4Dbdm9f1JxHEcHjf9M91B2RChjDEqkQFoGl3A5dz02bIcwgLEdb8InjvcE2QTh9bwQcysRmv43xakH9LBIAly4vJdQKE7Sc7hYp4zVwSyZLTgyoGXUCuQetI8WXHeaIWSPuNnBeGn7BbpL5DHPPXYQU4YQDhgqQ0G8lJboqa5G4AidOhGIRJV9htZJvWfKWLtRJjQtxZyGBz0UMePlqu1RmrJvrusITMy0PFXz3qexevKElv3EdaRVFkOrlqayuQhhQOvnRl9FYLsEwl3wKdRWBxGMYhZYv4agVJeVCCg2Sqe7d3nUVpL8CuodYIPJZHdtrKOeMJb3oKqT7l5Ge9DnMsek6kaMZTHqun6QjNDDPVxhs8sb1k3arvRlM461Ah0TtyBzt0zmlFme97YANtjvXoY8JR3vHiV03twCNnKwyhIhvf1cq9miakyhRLMtjZUlEKe0XCf9VL2p5OesqQKANXmeUjn1R2XmLeplcoboeuVscoV2cVPvdsOr6BwONBXSCVa1HYpfQDyyj1nDKKmqf0WefF2Wi6YAdpe24MutgW8lSlsPOEQoYMFLOLdnyWC8ZXpyv1cNaEKnXKy38J3biAS6748vhfxRJglMQddVOV8II7TYSzBY9mMQnxPC9XshfXzhE79Dhbe2MdI9NWhhyBRKPQImImQFrYiTGvvO2Hd2EWZTKSMaawfCCO6fjK09qMRoPfKW6bkp2OjurEEhL34HoUALzcU2C2Qib2cKb25jWMdAUbsMzDJz4qd77FV1HdVEMJsGNbhRthKuAg3Y0o3cSL2rsswhZ7ze2VGXbY2cS4f5qnjCd0qRn53dbNWZ7esgvU8P4zYJSE6ZpIYZZjaJyNNvtXvkRVtrUxvEwQdN1SxiKR06ptjQ6KyaFNthV88AUUykcP0yo8vwqDlrg5oMgac1ahfSKOzqNJxSCfTng5phCkgbs7yJmvJ0U5dASTi3Gi7trOoDJC6vKbfRAWMJHhSSgVw4hAGNYIbaX9pXGya8LKlnVPSDqh5XzKb2IbtAaMhjj20TQ281G6KgizwHUyDYKuaoX7r1iF1o5KlvSD1AYGuQKj8fH0JOGXZArVYJQgpeGvOatpb7kQVqkjBaUScqYgV5trRQ4W9L8gsG5YXE38CsFuQb1KwUIEn2WgIVNU6L7BElmYovmsS56BarbiPzfJJI8cL2AOjQ8Utg7uHleZwbkuol0GX4RtDg06mO
  PankoPassword: mJ4W8qDXjPn3UxbjU6a9tORoC
  PcsdPassword: 1vPfHGVO4hrhick2
  PlacementPassword: lmcsMl8Bz8ATZ5I8AfRxal56L
  RabbitCookie: yzAiVZfKu56JStkcTUEZ
  RabbitPassword: t7WfGmlXEe7U5Ml1yq3ouVIdu
  RedisPassword: WSHwPQSbJep9GaVSIdqqv6EJx
  RpcPassword: R0L82K1Ub2teP4KZSKqI0GR7b
  SaharaPassword: 97zJypeBt228vIWN8EogRxVh0
  SnmpdReadonlyUserPassword: 4vm720JEQIWQ0tcTIaAK0PTB
  SwiftHashSuffix: dUo1YWKs1Vaygo1XlHuykJKHb
  SwiftPassword: ktlXa9bHi7h6plx9vsKXDBnB2
  ZaqarPassword: JArgh9NxYG2jpUEWPBuxNVLDI
template: overcloud.yaml
version: '1.0'
