heat_template_version: rocky

description: >
  Post-deployment for the TripleO undercloud

parameters:
  servers:
    type: json

resources:
  OvercloudMinimalInitConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: {get_file: ./cloud-prepare-scripts/playbooks/init.sh}

  OvercloudMinimalInitDeployment:
    type: OS::Heat::SoftwareDeployments
    properties: 
      name: OvercloudMinimalInitDeployment
      servers: {get_param: [servers, 0]}
      config: {get_resource: OvercloudMinimalInitConfig}

