heat_template_version: rocky

description: >
  Hello-world container

parameters:
  ContainerHelloWorldPuppetImage:
    default: ''
    description: no description
    type: string
  ServiceData:
    default: {}
    description: Dictionary packing service data
    type: json
  ServiceNetMap:
    default: {}
    type: json
  RoleName:
    default: ''
    description: Role name on which the service is applied
    type: string
  RoleParameters:
    default: {}
    description: Parameters specific to the role
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    type: json

outputs:
  role_data:
    description: hello-world container start
    value:
      service_name: hello_world_puppet
      upgrade_tasks: []
      step_config: ''
      docker_config:
        step_4:
          hello_world_puppet:
            image: {get_param: ContainerHelloWorldPuppetImage}
            net: host
            privileged: none
      puppet_config:
        puppet_tags: file
        config_volume: /var/lib/config-data/puppet-generated/hello_world
        config_image: {get_param: ContainerHelloWorldPuppetImage}
        step_config: ''
