heat_template_version: rocky

description: >
  Hello-world ansible

parameters:
  ServiceData:
    default: {}
    description: Dictionary packing service data
    type: json
  ServiceNetMap:
    default: {}
    type: json
  RoleName:
    default: ''
    description: Role name on which the service is applied
    type: string
  RoleParameters:
    default: {}
    description: Parameters specific to the role
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    type: json

outputs:
  role_data:
    description: Motd role using composable services.
    value:
      # service_name: motd
      # config_settings:
      #  motd::content: {get_param: MotdMessage}
      #step_config: |
      #  if hiera('step') >= 2 {
      #    include ::motd
      #  }
      service_name: hello-world
      config_settings:
        tripleo::rhsm::firewall_rules: {}
      upgrade_tasks: []
      step_config: ''
      host_prep_tasks:
        - name: Red Hat Subscription Management configuration
          block:
          - include_role:
              name: michman
